version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: localmind_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: localmind_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./src/backend/backend.Dockerfile
    container_name: localmind_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRESQL_URL: postgresql+asyncpg://postgres:admin@db:5432/localmind_db
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ./src/frontend/frontend.Dockerfile
    container_name: localmind_frontend
    restart: unless-stopped
    ports:
      - "5500:80"
    depends_on:
      - backend

volumes:
  postgres_data:
