"""add deleted_at field to all models

Revision ID: 7a0d09a6f69c
Revises: 
Create Date: 2026-05-31 21:30:09.075582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0d09a6f69c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('conversations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('personality', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('user_oauth_tokens', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('user_oauth_tokens', 'deleted_at')
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'personality')
    op.drop_column('conversations', 'deleted_at')
    op.drop_column('attachments', 'deleted_at')
    # ### end Alembic commands ###
