"""add preview usage turn tracking to user model

Revision ID: ad89e00a444f
Revises: 7a0d09a6f69c
Create Date: 2026-06-01 18:04:30.936940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad89e00a444f'
down_revision: Union[str, Sequence[str], None] = '7a0d09a6f69c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preview_turn_useds', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('max_preview_turn', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_preview_turn')
    op.drop_column('users', 'preview_turn_useds')
    # ### end Alembic commands ###
